Add missing `tmpdir` to fix NoMethodError
> NoMethodError: undefined method `mktmpdir' for Dir:Class

--- https://circleci.com/gh/sider/runners/56990

See https://stackoverflow.com/a/58036781