Fix error for issue sorting when location is nil
[`Array#sort_by!`](http://ruby-doc.org/core-2.6.5/Array.html#method-i-sort_by-21) raises the following error
when `nil` is included as a member of an array.

> ArgumentError: comparison of Array with Array failed